import { Router, type IRouter } from "express";
import healthRoutes from "./healthRoutes";
import authRoutes from "./authRoutes";
import usersRoutes from "./usersRoutes";
import leadsRoutes from "./leadsRoutes";
import callsRoutes from "./callsRoutes";
import dealsRoutes from "./dealsRoutes";
import documentsRoutes from "./documentsRoutes";
import statsRoutes from "./statsRoutes";
import importRoutes from "./importRoutes";
import analysisRoutes from "./analysis";
import fundersRoutes from "./fundersRoutes";
import submissionsRoutes from "./submissionsRoutes";
import stipulationsRoutes from "./stipulationsRoutes";
import activitiesRoutes from "./activitiesRoutes";
import commissionsRoutes from "./commissionsRoutes";
import referralSourcesRoutes from "./referral-sourcesRoutes";
import searchRoutes from "./searchRoutes";
import notificationsRoutes from "./notificationsRoutes";
import templatesRoutes from "./templatesRoutes";
import analyticsRoutes from "./analyticsRoutes";
import aiLearningRoutes from "./ai-learningRoutes";
import portfolioRoutes from "./portfolioRoutes";
import advancedRoutes from "./advancedRoutes";
import googleSheetsRoutes from "./google-sheetsRoutes";
import aiRoutes from "./ai";
import webhooksRoutes from "./webhooksRoutes";
import rolePermissionsRoutes from "./role-permissionsRoutes";
import smartRemindersRoutes from "./smart-remindersRoutes";
import messagingRoutes from "./messagingRoutes";
import reportsRoutes from "./reportsRoutes";
import tasksRoutes from "./tasksRoutes";
import phoneNumbersRoutes from "./phone-numbersRoutes";
import securityRoutes from "./securityRoutes";
import distributionRoutes from "./distributionRoutes";

const router: IRouter = Router();

router.use(healthRoutes);
router.use(authRoutes);
router.use(usersRoutes);
router.use(leadsRoutes);
router.use(callsRoutes);
router.use(dealsRoutes);
router.use(documentsRoutes);
router.use(statsRoutes);
router.use(importRoutes);
router.use(analysisRoutes);
router.use(fundersRoutes);
router.use(submissionsRoutes);
router.use(stipulationsRoutes);
router.use(activitiesRoutes);
router.use(commissionsRoutes);
router.use(referralSourcesRoutes);
router.use(searchRoutes);
router.use(notificationsRoutes);
router.use(templatesRoutes);
router.use(analyticsRoutes);
router.use(aiLearningRoutes);
router.use(portfolioRoutes);
router.use(advancedRoutes);
router.use(googleSheetsRoutes);
router.use(aiRoutes);
router.use(webhooksRoutes);
router.use(rolePermissionsRoutes);
router.use(smartRemindersRoutes);
router.use(messagingRoutes);
router.use(reportsRoutes);
router.use(tasksRoutes);
router.use(phoneNumbersRoutes);
router.use(securityRoutes);
router.use(distributionRoutes);

export default router;
