kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "artifacts/api-server"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "pnpm --filter @workspace/server run dev"

[services.production]
build = "pnpm --filter @workspace/server run build"

[services.production.run]
args = ["node", "--expose-gc", "--max-old-space-size=3072", "artifacts/api-server/dist/index.cjs"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/api/healthz"
