import { pgTable, text, serial, timestamp, integer, numeric, boolean, jsonb, uniqueIndex, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { usersTable } from "./users";

export const leadsTable = pgTable("leads", {
  id: serial("id").primaryKey(),
  businessName: text("business_name").notNull(),
  dba: text("dba"),
  ownerName: text("owner_name").notNull(),
  email: text("email"),
  phone: text("phone").notNull(),
  status: text("status").notNull().default("new"),
  assignedToId: integer("assigned_to_id").references(() => usersTable.id),
  requestedAmount: numeric("requested_amount", { precision: 20, scale: 2 }),
  monthlyRevenue: numeric("monthly_revenue", { precision: 20, scale: 2 }),
  industry: text("industry"),
  businessType: text("business_type"),
  ownershipPct: numeric("ownership_pct", { precision: 20, scale: 2 }),
  businessStartDate: text("business_start_date"),
  address: text("address"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  homeAddress: text("home_address"),
  homeCity: text("home_city"),
  homeState: text("home_state"),
  homeZip: text("home_zip"),
  ein: text("ein"),
  yearsInBusiness: numeric("years_in_business", { precision: 20, scale: 2 }),
  notes: text("notes"),

  ssn: text("ssn"),
  ssnHash: text("ssn_hash"),
  dob: text("dob"),
  taxId: text("tax_id"),
  driversLicense: text("drivers_license"),
  dlState: text("dl_state"),
  dlExpiry: text("dl_expiry"),
  creditScore: integer("credit_score"),
  riskCategory: text("risk_category"),
  avgDailyBalance: numeric("avg_daily_balance", { precision: 20, scale: 2 }),
  hasExistingLoans: boolean("has_existing_loans"),
  loanCount: integer("loan_count").default(0),
  totalLoanPayments: numeric("total_loan_payments", { precision: 20, scale: 2 }).default("0"),
  loanDetails: jsonb("loan_details"),
  revenueTrend: text("revenue_trend"),
  grossRevenue: numeric("gross_revenue", { precision: 20, scale: 2 }),
  position: integer("position").default(1),
  bankName: text("bank_name"),
  accountNumber: text("account_number"),
  routingNumber: text("routing_number"),
  referralSourceId: integer("referral_source_id"),
  importBatchId: integer("import_batch_id"),
  importDate: timestamp("import_date", { withTimezone: true }),
  source: text("source").default("manual"),

  isHot: boolean("is_hot").default(false),
  hotTriggeredAt: timestamp("hot_triggered_at", { withTimezone: true }),
  estimatedApproval: numeric("estimated_approval", { precision: 20, scale: 2 }),
  approvalConfidence: integer("approval_confidence"),
  bankStatementsStatus: text("bank_statements_status").default("none"),
  bankStatementMonths: jsonb("bank_statement_months"),
  sourceTier: text("source_tier"),
  hasOnDeck: boolean("has_on_deck").default(false),
  sheetWritebackStatus: text("sheet_writeback_status"),
  term: integer("term"),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastContactedAt: timestamp("last_contacted_at", { withTimezone: true }),
}, (table) => [
  index("leads_assigned_to_idx").on(table.assignedToId),
  index("leads_status_idx").on(table.status),
  index("leads_business_name_idx").on(table.businessName),
  index("leads_created_at_idx").on(table.createdAt),
  index("leads_import_batch_idx").on(table.importBatchId),
  index("leads_risk_category_idx").on(table.riskCategory),
  index("leads_is_hot_idx").on(table.isHot),
  index("leads_source_idx").on(table.source),
  index("leads_bank_statements_status_idx").on(table.bankStatementsStatus),
  index("leads_referral_source_idx").on(table.referralSourceId),
]);

export const insertLeadSchema = createInsertSchema(leadsTable).omit({ id: true, createdAt: true, lastContactedAt: true });
export type InsertLead = z.infer<typeof insertLeadSchema>;
export type Lead = typeof leadsTable.$inferSelect;
